double evaluate(const char *expr);
double term();
double exponent();
double factor();
double logarithms();
double trig();
double number();
double expression();
double expression();
char get();
char peek();
extern char *quickmafs_buffer;
